fullscreen_button = 0
use_css_perso = 0
trackmap_disp_timelost = 0
trackmap_disp_north = 0
trackmap_disp_wind = 0
trackmap_disp_weather_infos = 0
trackmap_thickness_coef = 1.6
transparence_fond_trackmap = 0
trackmap_bg_img = 1
trackmap_outline_disp = 1
trackmap_outline_coef = 2
trackmap_car_coef = 1.3
trackmap_carnum_coef = 1.3
trackmap_car_me_specify = 1
window_x = 2572
window_y = 19
window_w = 623
window_h = 382
window_click_through = 1
show_overlay_sim_not_running = 0
show_overlay_not_incar = 0
show_overlay_ingarage = 0
overlay_hide_joy = 'Keyboard_1'
overlay_hide_button = ["Alt", "S", "Shift"]

broadcast=2
fps_broadcast=0.4